/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

/*
 * Author: Vikash@KTree.com
 * Date  : 26th May 2015
 */

package com.ktree.timezone.model.dao.model.impl;

import com.ktree.timezone.model.dao.model.WorldClock;
import com.ktree.timezone.model.dao.service.WorldClockLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the WorldClock service. Represents a row in the &quot;table_WorldClock&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WorldClockImpl}.
 * </p>
 *
 * @author vikash@KTree
 * @see WorldClockImpl
 * @see com.ktree.timezone.model.dao.model.WorldClock
 * @generated
 */
public abstract class WorldClockBaseImpl extends WorldClockModelImpl
	implements WorldClock {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a world clock model instance should use the {@link WorldClock} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			WorldClockLocalServiceUtil.addWorldClock(this);
		}
		else {
			WorldClockLocalServiceUtil.updateWorldClock(this);
		}
	}
}