/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ktree.timezone.model.dao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WorldClock service. Represents a row in the &quot;table_WorldClock&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ktree.timezone.model.dao.model.impl.WorldClockModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ktree.timezone.model.dao.model.impl.WorldClockImpl}.
 * </p>
 *
 * @author vikash@KTree
 * @see WorldClock
 * @see com.ktree.timezone.model.dao.model.impl.WorldClockImpl
 * @see com.ktree.timezone.model.dao.model.impl.WorldClockModelImpl
 * @generated
 */
public interface WorldClockModel extends BaseModel<WorldClock> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a world clock model instance should use the {@link WorldClock} interface instead.
	 */

	/**
	 * Returns the primary key of this world clock.
	 *
	 * @return the primary key of this world clock
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this world clock.
	 *
	 * @param primaryKey the primary key of this world clock
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this world clock.
	 *
	 * @return the ID of this world clock
	 */
	public int getId();

	/**
	 * Sets the ID of this world clock.
	 *
	 * @param id the ID of this world clock
	 */
	public void setId(int id);

	/**
	 * Returns the place of this world clock.
	 *
	 * @return the place of this world clock
	 */
	@AutoEscape
	public String getPlace();

	/**
	 * Sets the place of this world clock.
	 *
	 * @param place the place of this world clock
	 */
	public void setPlace(String place);

	/**
	 * Returns the timezone of this world clock.
	 *
	 * @return the timezone of this world clock
	 */
	public Date getTimezone();

	/**
	 * Sets the timezone of this world clock.
	 *
	 * @param timezone the timezone of this world clock
	 */
	public void setTimezone(Date timezone);

	/**
	 * Returns the userid of this world clock.
	 *
	 * @return the userid of this world clock
	 */
	public long getUserid();

	/**
	 * Sets the userid of this world clock.
	 *
	 * @param userid the userid of this world clock
	 */
	public void setUserid(long userid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WorldClock worldClock);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WorldClock> toCacheModel();

	@Override
	public WorldClock toEscapedModel();

	@Override
	public WorldClock toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}